probe:
  id: 6cbf09dc-e602-45ee-9c70-0a0b3b1cf16e
  label: "LIST capture probe"

rabbitmq:
  hostname: localhost
  port: 5672

# engine: recorder | tcpdump | dpdk | fromFile
engine: fromFile
# interfaces: <if_name> | <file_name> , ...
interfaces: ../../js/tests/pcaps/eemebe_t_1080i59.pcap
